apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: slack-codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slack-codelab
    spec:
      containers:
      - name: master
        image: gcr.io/inphooddb-e0dfd/slack-codelab:v1  # Replace PROJECT_ID
                                                        # with your project ID.
        volumeMounts:
        - name: slack-token
          mountPath: /etc/slack-token
        - name: firebase-token
          mountPath: /etc/firebase-token
        env:
        - name: slack_token_path
          value: /etc/slack-token/slack-token
        - name: firebase_token_path
          value: /etc/firebase-token/firebase-token
      volumes:
      - name: slack-token
        secret:
          secretName: slack-token
      - name: firebase-token
        secret:
          secretName: firebase-token
